# Generated by Django 2.2.5 on 2021-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('仕事', '仕事'), ('トピック', 'トピック'), ('定年', '定年'), ('人生', '人生'), ('健康', '健康'), ('趣味', '趣味'), ('家庭', '家庭')], max_length=150, null=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
